//! SQL emission (ac-05). Turn a [`Detection`] into a standalone DuckDB `.sql`
//! that loads the input natively. The SQL is plain and reviewable — legibility
//! is the output value (the tabletop's load-bearing value): a reviewer reads
//! exactly which reader and parameters run, with no cleverness to decode.
//!
//! Emission never touches DuckDB — it produces text. DuckDB executes only in the
//! round-trip test (ac-07), never on survey's own path (choice 0001).

use crate::structure::{Detection, Format, Structure};

/// The duplicate-column policy survey records when an input has repeated column
/// names (ac-11). `Rename` is the default — deterministic, and keeps every
/// column's data rather than dropping silently (review-spec finding 4).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DuplicatePolicy {
    Rename,
    KeepFirst,
    KeepLast,
}

impl Default for DuplicatePolicy {
    fn default() -> Self {
        DuplicatePolicy::Rename
    }
}

/// A single-quoted SQL string literal with embedded quotes escaped.
fn sql_str(s: &str) -> String {
    format!("'{}'", s.replace('\'', "''"))
}

/// Build the `read_*` table function call for a detection, with the parameters
/// the detector resolved.
fn read_call(det: &Detection, source: &str) -> String {
    match det.format {
        Format::Csv => format!("read_csv({}, header = true, delim = ',')", sql_str(source)),
        Format::Tsv => format!("read_csv({}, header = true, delim = '\\t')", sql_str(source)),
        Format::Parquet => format!("read_parquet({})", sql_str(source)),
        Format::Ndjson => {
            format!("read_json({}, format = 'newline_delimited')", sql_str(source))
        }
        Format::Json => match det.structure {
            Structure::RecordsArray => format!("read_json({}, format = 'array')", sql_str(source)),
            // A single top-level object is one row; 'auto' lets DuckDB read the
            // object as a single record.
            Structure::SingleObject => format!("read_json({}, format = 'auto')", sql_str(source)),
            Structure::FlatTable => format!("read_json({}, format = 'auto')", sql_str(source)),
        },
    }
}

/// Emit a standalone `.sql` that loads `source` into `table_name`, given the
/// detection and a duplicate-column policy.
pub fn emit_sql(
    det: &Detection,
    source: &str,
    table_name: &str,
    policy: DuplicatePolicy,
) -> String {
    let mut sql = String::new();
    sql.push_str("-- Generated by dovetail survey\n");
    sql.push_str(&format!("-- source: {source}\n"));
    sql.push_str(&format!(
        "-- format: {:?}  structure: {:?}  rung: sql\n",
        det.format, det.structure
    ));
    if !det.duplicate_columns.is_empty() {
        sql.push_str(&format!(
            "-- duplicate columns {:?} handled by policy: {:?}\n",
            det.duplicate_columns, policy
        ));
    }
    sql.push('\n');

    let read = read_call(det, source);

    // The duplicate-rename policy projects the read with disambiguated names so
    // no column's data is dropped. With no duplicates (the common case) the load
    // is a plain SELECT *.
    if det.duplicate_columns.is_empty() || policy != DuplicatePolicy::Rename {
        sql.push_str(&format!(
            "CREATE OR REPLACE TABLE {table_name} AS\nSELECT * FROM {read};\n"
        ));
    } else {
        let projection = renamed_projection(det);
        sql.push_str(&format!(
            "CREATE OR REPLACE TABLE {table_name} AS\nSELECT {projection}\nFROM {read};\n"
        ));
    }
    sql
}

/// Build a `col, col_2, ...` projection that disambiguates duplicate column
/// names positionally. DuckDB's reader suffixes duplicate columns itself
/// (`name`, `name_1`, ...); this projection names them explicitly so the emitted
/// SQL is self-documenting about the rename.
fn renamed_projection(det: &Detection) -> String {
    let mut counts: std::collections::HashMap<&str, usize> = std::collections::HashMap::new();
    let mut parts = Vec::new();
    for col in &det.columns {
        let n = counts.entry(col.name.as_str()).or_insert(0);
        if *n == 0 {
            parts.push(quote_ident(&col.name));
        } else {
            // DuckDB exposes the k-th duplicate as `name_{k}`; alias it explicitly.
            let src = format!("{}_{}", col.name, n);
            parts.push(format!("{} AS {}", quote_ident(&src), quote_ident(&src)));
        }
        *n += 1;
    }
    parts.join(", ")
}

/// Double-quote a SQL identifier, escaping embedded quotes.
fn quote_ident(s: &str) -> String {
    format!("\"{}\"", s.replace('"', "\"\""))
}
